language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  exclude:
    - php: hhvm
      env: COMPOSER_OPTS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --dev $COMPOSER_OPTS

script:
  - vendor/bin/behat -f progress --strict
